### ISSUE TITLE
Firefox Setup

### ISSUE THREAD

**Issue by Glutamat42** [tjhorner/archivebox-exporter#11]
To make the plugin work (at least on firefox with a password protected ArchiveBox-setup) a checkbox in the extension settings has to be enabled (allow access to data of all websites, see screenshot below). Otherwise it wont work without an error message.  Maybe this should be added to the setup instructions (readme and in the extension store).

![grafik](https://user-images.githubusercontent.com/51326311/129915539-764844ea-b6a0-4d04-a8ef-6dcc628553f1.png)

It might also be good to make clearer you have to login to archivebox.

**Comment by tjhorner** [comment]
That's weird; it's supposed to ask you for permission automatically through [`permissions.request`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request). You shouldn't have to do this automatically. This is how it looks on Chrome:

![image](https://user-images.githubusercontent.com/2646487/129969635-7094975a-1529-436f-8865-f7895216ee85.png)

And it looks like this API is supported on Firefox, so I'm not sure why it's not working. Thanks for the report. I'll look into this and see what's up.

**Comment by tjhorner** [comment]
I published 1.3.1 which adds the `*://*/*` permission as non-optional, so you shouldn't need to manually grant it anymore. It's currently under review by Mozilla.

**Comment by tjhorner** [comment]
Well, that was fast. 1.3.1 is up on the addons store.
