### ISSUE TITLE
CSRF Token Missing Error

### ISSUE THREAD

**Issue by nickwinn** [tjhorner/archivebox-exporter#14]
I'm a new archivebox user, but on a fresh install, receiving this error when trying to send pages to archivebox.

`archivebox_1  | Forbidden (CSRF token missing or incorrect.): /add/`

Running archivebox from docker hub tagged master (archivebox/archivebox:master). 

Using Firefox 91.4.1esr (64-bit) and I'm signed in on other tabs in archivebox. I'm wondering if this is a new security feature of the latest firefox release. 

Any help is appreciated.

**Comment by tjhorner** [comment]
From the readme:

> **⚠️ Note:** At the moment, the changes required for this extension to work are not yet merged into the stable release of ArchiveBox, so you will need to run the `dev` branch by following the steps [outlined here](https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch).

Let me know if you run into any issues with this process

**Comment by tjhorner** [comment]
It looks like there's an image on Docker Hub tagged with `dev`, so you should be able to use `archivebox/archivebox:dev`

**Comment by p6002** [comment]
Still not work.
`CSRF Token Missing Error`
