### ISSUE TITLE
Transmitt data instead of transmitting url

### ISSUE THREAD

**Issue by esp13** [tjhorner/archivebox-exporter#16]
Hi,

Some web-pages I want to backup are behind a two factors authentication protection or are dispatched from a local network (where the archivebox server doesn't belongs).
So I wonder if there is a way that the browser (firefox for my exemple) send the data (html, images, videos, files, etc...) through the extension instead of just sharing the link that will not be enough to access the data?

I hope I didn't missed it?

**Comment by pirate** [comment]
You're better off using something like 22120, ArchiveWeb.page, or the Memex browser extension imo.

**Comment by tjhorner** [comment]
Closing since ArchiveBox does not support this. Will re-open if that changes
