### ISSUE TITLE
Addon no longer works?

### ISSUE THREAD

**Issue by p6002** [tjhorner/archivebox-exporter#20]
I tried adding to the Edge browser extension:

```
serverip:port

serverip:port/admin

serverip:port/admin/core

archive.mydomain.com

archive.mydomain.com:port

archive.mydomain.com/admin

archive.mydomain.com/admin/core

```
With and without http/https - no success. I can't manually or automatically add pages to download.

I activated the cli option to use without login as it says in the documentation. 

When I add the page manually through the site, it downloads correctly. The problem is only with the browser addon.

**Comment by pirate** [comment]
Can you share the output of `archivebox --version` and your `./data/logs/*.log` log files around the time when you're clicking archive from the extension?

**Comment by p6002** [comment]
Version:
https://pastebin.com/MtNx0p56
Error.log (only file in log directory) 
https://pastebin.com/y17RWHp6

**Comment by pirate** [comment]
Can you try with the dev version instead of master? set it to `archivebox/archivebox:dev` and then do `docker-compose pull`.

**Comment by p6002** [comment]
No changes:
https://pastebin.com/9EvFhspY

**Comment by pirate** [comment]
can you try setting `archivebox config --set SAVE_MERCURY=False` and try again, seems there might be an issue with the mercury article text extractor.

**Comment by p6002** [comment]
Still nothing, here is output:

`root@f7704c11dd33:/data# su archivebox
$ archivebox config --set SAVE_MERCURY=False
find: '/.config/chromium/Crash Reports/pending/': No such file or directory
[i] [2023-02-21 19:23:08] ArchiveBox v0.6.3: archivebox config --set SAVE_MERCURY=False
    > /data

find: '/.config/chromium/Crash Reports/pending/': No such file or directory
find: '/.config/chromium/Crash Reports/pending/': No such file or directory
find: '/.config/chromium/Crash Reports/pending/': No such file or directory
SAVE_MERCURY=False

[i] Note: This change also affected these other options that depended on it:
    USE_MERCURY=False
$ `

**Comment by p6002** [comment]
Here is screenshot:
https://i.ibb.co/2NLWJpD/2023-02-25-002708.png\

Of course, instead of domain is my domain. I can still manually add the page in the app.
This is what the compose file looks like from where I run the container:
https://pastebin.com/QdCqDwFw

**Comment by pirate** [comment]
Can you try with 8000 just to test temporarily instead of 8505, maybe it's a port mapping issue? I've seen issues with non-default ports in the past.

**Comment by p6002** [comment]
I changed to 1209 and still the same thing. I have the firewall on the Synology turned off. Overall I have about 40 containers on different configurations and everything works. Archivebox also works in the browser, only the plugin does not connect.

I'm using the Edge browser on Windows, but I also tested in Firefox on Ubuntu and there is the same problem. 

When I just add https://mydomain.com/ the task number on the addon icon just blinks. 

If I add https://mydomain.com:1209/ then the number 1 on the icon lights up for a few seconds, but it doesn't change anything. 

Yesterday I was still using Nginx proxy manager, but I changed to Synology's built-in reverse proxy and it didn't help at all. 

Maybe some other browser plugin or setting is blocking this connection?

**Comment by pirate** [comment]
Thats a great sign, it's getting the `/add/` submission at least. Are you sure you're adding unique URL's that arent already archived? ArchiveBox only archives URLs once, it doesn't re-snapshot if you already have the URL.

**Comment by p6002** [comment]
Do you have some working docker-compose file for this project?

**Comment by pirate** [comment]
The default one in the repo works.

**Comment by p6002** [comment]
Works good, but not work with browser addon.

**Comment by p6002** [comment]
I tested on firefox and the extension works fine. The problem exists only on Edge. 

What do you need to help you fix it?

**Comment by unmenschlich** [comment]
here it doesnt work.

Server:
docker bridge + port 8000 -> 8040 or host + port 8000 (can connect both with firefox)
archivebox/archivebox:dev
errorlog: https://pastebin.com/raw/XutpN9Kf

Firefox:
add base url and "add current domain to list" but nothing happens

**Comment by p6002** [comment]
This project hasn't been moved for 2 years, which is probably why it is no longer supported by browsers.

**Comment by unmenschlich** [comment]
oh, thank you for info

**Comment by pirate** [comment]
@p6002  We haven't had a major release because I have a refactor that's been slow-moving and touches a lot of pieces, and I care too much about not breaking backward compatibility to release it until it's finished.
In the meantime development and bugfixes have been ongoing in the `dev` branch. The `dev` branch works with this extension in browsers, I am using it right now :)

**Comment by gerroon** [comment]
This does not seem to work for me either on Brave. Can anyone please confirm this is supposed to be working or not with the latest dev branch of archive box?

**Comment by pirate** [comment]
I can confirm it's been working for a while and is currently working for me. 

Can you post your docker-compose.yml and the full output of `docker compose run archivebox version`.

**Comment by gerroon** [comment]
@pirate Thanks for the reply.

```
docker compose run archivebox version

chown: cannot access '/browsers/*': No such file or directory
0.7.1+editable

ArchiveBox v0.7.1+editable Cpython Linux Linux-5.14.0-4-amd64-x86_64-with-glibc2.36 x86_64
DEBUG=False IN_DOCKER=True IN_QEMU=False IS_TTY=True TZ=UTC FS_ATOMIC=True FS_REMOTE=True FS_USER=911:911 FS_PERMS=644 SEARCH_BACKEND=ripgrep

```

**Comment by pirate** [comment]
You need to set `docker compose run archivebox config --set PUBLIC_ADD_PAGE=True`

**Comment by gerroon** [comment]
I did not do that, the extension page did not mention it. I ran that command and restarted the container. I still have the same issue.

I can see it posts something but no nothing happens on the server. I can add urls manually in the server's own page but that is so much friction to have it open and accesible all the time.

```
archivebox_1  | "POST /add/ HTTP/1.1" 302 0
archivebox_1  | "GET /accounts/login/?next=/add/ HTTP/1.1" 302 0
archivebox_1  | "GET /admin/login/ HTTP/1.1" 200 11143
```


Is the extension using a REST API or doing some special server talk? I will try to look into it, although I am not a web dev. I can maybe make it work.

**Comment by pirate** [comment]
Can you post the full verbatim output of:
```bash
docker compose pull
docker compose run archivebox version
docker compose run archivebox config --set PUBLIC_ADD_PAGE=True
docker compose run archivebox config
docker compose down
docker compose down
docker compose up
docker compose logs
```

**Comment by mamema** [comment]
isn't the parameter PUBLIC_ADD_VIEW=True ?

**Comment by pirate** [comment]
Ah right sorry, I misremembered.

Here it is in the docs about the extension for future reference: https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#browser-extension-usage.

If anyone still needs help, please open a separate issue! 😁
